

version: '3'

services:

    web-storage:
        image: nosrt-storage/app
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db-storage
            - db-cache
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        networks:
            - sail

    db-storage:
        image: 'postgres:15'
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgres/data'
        networks:
            - sail

    db-cache:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local



