
version: '3'

#include:
#   - path:
#       - ./db-storage.yaml
#       - ./db-cache.yaml

services:

    storage-app:
        image: nosrt-storage/app
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        hostname: localhost
        ports:
            - '${APP_PORT:-80}:${APP_PORT:-80}'
            - '${VITE_PUSHER_PORT:-5173}:5173'  # vite for tailwindcss includes
        volumes:
            - '.:/var/www/html'
        depends_on:
            - db-storage
            - db-cache
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        networks:
            - sail

    db-storage:
        image: 'postgres:15'
        ports:
            - '${DB_PORT:-5432}:${DB_PORT:-5432}'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgres/data'
        networks:
            - sail

    db-cache:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local



